-- Controlled starter batch collected from official firm websites on 2026-08-11.
-- Run only after the Phase 2 migration. Records remain staged for human review.
with job as (
  insert into public.discovery_jobs(city,market,region,search_category,search_query,source,status,records_found,started_at,completed_at)
  values('San Antonio','Central Texas','San Antonio','Small Business Accountant','accounting, CPA, bookkeeping, EA and CAS firms San Antonio TX','Official firm websites','Complete',15,now(),now()) returning id
)
insert into public.firm_candidates(discovery_job_id,firm_name,website,phone,address_line_1,city,region,market,possible_firm_type,source,source_url,description,confidence)
select job.id,v.* from job cross join (values
('Mason Tax & Business Solutions','https://masontbs.com/','(210) 349-0092','2008 NW Military Hwy','San Antonio','San Antonio','Central Texas','Enrolled Agent','Official firm website','https://masontbs.com/','Tax, accounting and financial consulting firm serving small- and medium-sized businesses.','High'::public.confidence_level),
('Rodriguez Reiffert & Co., P.C.','https://www.cpasat.com/',null,null,'San Antonio','San Antonio','Central Texas','CPA Firm','Official firm website','https://www.cpasat.com/','San Antonio CPA firm advertising business accounting and tax services for small businesses.','High'::public.confidence_level),
('SA Small Business Accounting & Tax, Inc.','https://www.sasmallbusiness.com/','(210) 481-7100','13750 San Pedro Road, Suite 645','San Antonio','San Antonio','Central Texas','Accounting Firm','Official firm website','https://www.sasmallbusiness.com/','Small-business accounting, tax and QuickBooks services.','High'::public.confidence_level),
('INK & LEDGER TAX SOLUTIONS LLC','https://inkandledger.org/',null,null,'San Antonio','San Antonio','Central Texas','Tax Firm','Official firm website','https://inkandledger.org/','Tax and bookkeeping services for individuals and small businesses.','High'::public.confidence_level),
('Small Business Services of San Antonio','https://www.sbsofsa.com/','(210) 884-5067','101 Sunflower Lane','San Antonio','San Antonio','Central Texas','Bookkeeper','Official firm website','https://www.sbsofsa.com/','Bookkeeping, payroll, tax preparation and CFO/tax advisory for small businesses.','High'::public.confidence_level),
('True Books','https://www.truebooksonline.com/',null,null,'San Antonio','San Antonio','Central Texas','Bookkeeper','Official firm website','https://www.truebooksonline.com/','Owner-led San Antonio bookkeeping service focused on small-business financial independence.','High'::public.confidence_level),
('Bulverde Business Solutions','https://www.bulverdebusiness.com/',null,null,'San Antonio','San Antonio','Central Texas','CAS / Advisory','Official firm website','https://www.bulverdebusiness.com/','Bookkeeping, reporting, payroll/HR infrastructure and business coaching for small businesses.','High'::public.confidence_level),
('Petry Bookkeeping','https://petrybookkeeping.com/',null,null,'San Antonio','San Antonio','Central Texas','Bookkeeper','Official firm website','https://petrybookkeeping.com/','Professionally managed bookkeeping for small and midsized businesses in San Antonio and surrounding markets.','High'::public.confidence_level),
('Tax Consultants of San Antonio','https://www.taxconsultantsofsanantonio.com/',null,null,'San Antonio','San Antonio','Central Texas','Enrolled Agent','Official firm website','https://www.taxconsultantsofsanantonio.com/','Enrolled Agent practice offering IRS representation, tax help and small-business tax services.','High'::public.confidence_level),
('Britts & Associates, LLP','https://www.cpasatx.com/',null,null,'San Antonio','San Antonio','Central Texas','CPA Firm','Official firm website','https://www.cpasatx.com/','Full-service CPA firm offering bookkeeping, tax, assurance, payroll and advisory services to small businesses.','High'::public.confidence_level),
('Wilder Bookkeeping','https://www.wilderbk.com/',null,null,'San Antonio','San Antonio','Central Texas','Bookkeeper','Official firm website','https://www.wilderbk.com/','Professional bookkeeping services for San Antonio small businesses and nonprofits.','High'::public.confidence_level),
('Axis Mobile Bookkeeping','https://www.axismb.org/',null,null,'San Antonio','San Antonio','Central Texas','Bookkeeper','Official firm website','https://www.axismb.org/','Veteran-owned bookkeeping provider serving San Antonio and the Hill Country.','High'::public.confidence_level),
('West Wind Accounting, PC','https://www.westwindcpa.com/',null,null,'San Antonio','San Antonio','Central Texas','Accounting Firm','Official firm website','https://www.westwindcpa.com/','Texas accounting firm providing tax, bookkeeping and advisory services.','High'::public.confidence_level),
('1604 Tax & Accounting Group','https://1604tax.com/',null,null,'San Antonio','San Antonio','Central Texas','Enrolled Agent','Official firm website','https://1604tax.com/','San Antonio tax and accounting practice led by a licensed Enrolled Agent.','High'::public.confidence_level),
('Debra R. Quintanilla CPA PC','https://www.drqcpa.com/',null,'5825 Callaghan Road #100','San Antonio','San Antonio','Central Texas','CPA Firm','Official firm website','https://www.drqcpa.com/','Full-service CPA and consulting practice advertising small-business accounting and bookkeeping.','High'::public.confidence_level)
) as v(firm_name,website,phone,address_line_1,city,region,market,possible_firm_type,source,source_url,description,confidence);
