import { NextResponse } from "next/server";
import { processCandidateWebResearch } from "@/lib/discovery/web-research";
import { createAdminClient, createClient } from "@/lib/supabase/server";

export const maxDuration=300;

export async function GET(_request:Request,context:{params:Promise<{id:string}>}){const{id}=await context.params;const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:"Authentication required."},{status:401});const[{data:runs,error:runError},{data:findings,error:findingError}]=await Promise.all([supabase.from("candidate_research_runs").select("*").eq("firm_candidate_id",id).order("created_at",{ascending:false}),supabase.from("candidate_research_findings").select("*").eq("firm_candidate_id",id).order("category").order("created_at")]);if(runError||findingError)return NextResponse.json({error:"Research details could not be loaded."},{status:500});return NextResponse.json({runs:runs??[],findings:findings??[]});}

export async function POST(_request:Request,context:{params:Promise<{id:string}>}){const{id}=await context.params;const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:"Authentication required."},{status:401});const admin=createAdminClient();const{data:candidate}=await admin.from("firm_candidates").select("id,review_status,domain,website").eq("id",id).maybeSingle<{id:string;review_status:string;domain:string|null;website:string|null}>();if(!candidate||!["New","Needs Review"].includes(candidate.review_status)||!(candidate.domain||candidate.website))return NextResponse.json({error:"This candidate needs an official website before web research can run."},{status:409});const{data:existing}=await admin.from("candidate_research_runs").select("id,status").eq("firm_candidate_id",id).in("status",["Queued","Running","Retry"]).order("created_at",{ascending:false}).limit(1).maybeSingle<{id:string;status:string}>();if(existing?.status==="Running")return NextResponse.json({error:"Research is already running for this candidate."},{status:409});let runId=existing?.id;if(!runId){const{data:created,error}=await admin.from("candidate_research_runs").insert({firm_candidate_id:id,requested_by:user.id}).select("id").single<{id:string}>();if(error)return NextResponse.json({error:"This candidate could not be queued for research."},{status:409});runId=created.id;}await admin.from("firm_candidates").update({web_research_status:"Queued",web_research_error_code:null}).eq("id",id).neq("web_research_status","Researching");try{const result=await processCandidateWebResearch(id);if(result.claimed===0){const{data:state}=await admin.from("firm_candidates").select("web_research_status").eq("id",id).single<{web_research_status:string}>();if(state?.web_research_status==="Daily Limit")return NextResponse.json({error:"The daily web-research limit has been reached. Try again tomorrow."},{status:429});return NextResponse.json({error:"This queued research run is not ready yet. Try again shortly."},{status:409});}const[{data:state},{data:run}]=await Promise.all([admin.from("firm_candidates").select("web_research_status").eq("id",id).single<{web_research_status:string}>(),admin.from("candidate_research_runs").select("status,error_code,pages_visited").eq("id",runId).single<{status:string;error_code:string|null;pages_visited:number}>()]);return NextResponse.json({runId,status:state?.web_research_status??run?.status??"Complete",pagesVisited:run?.pages_visited??0,errorCode:run?.error_code??null});}catch(workerError){const code=workerError&&typeof workerError==="object"&&"code" in workerError?String(workerError.code):"unknown";console.error(`[Web Research] targeted worker failed (code: ${code})`);return NextResponse.json({error:"Web research could not be started."},{status:500});}}
