import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { detectDuplicate, isMailMergeEligible, normalizeDomain, recommendPartnerType } from "../lib/discovery/core.mjs";

const migration = await readFile(new URL("../supabase/migrations/20260811000000_phase_1.sql", import.meta.url), "utf8");
const seed = await readFile(new URL("../supabase/seed.sql", import.meta.url), "utf8");
const phase2 = await readFile(new URL("../supabase/migrations/20260811010000_phase_2_discovery_enrichment.sql", import.meta.url), "utf8");
const candidates = await readFile(new URL("../lib/discovery/real-candidates.ts", import.meta.url), "utf8");

test("schema contains all Phase 1 relational tables", () => {
  for (const table of ["firms","contacts","outreach","tags","firm_tags","import_batches"]) assert.match(migration, new RegExp(`create table public\\.${table}`));
});
test("RLS is enabled and anonymous access is revoked", () => { assert.equal((migration.match(/enable row level security/g)||[]).length,6); assert.match(migration,/revoke all .* from anon/); });
test("deduplication indexes cover firm domain, firm name-city, contact email, and contact name", () => { for (const name of ["firms_domain_unique","firms_name_city_unique","contacts_firm_email_unique","contacts_firm_name_unique"]) assert.match(migration,new RegExp(name)); });
test("score caps at 100 and assigns all four grades", () => { assert.match(migration,/least\(score,100\)/); for(const grade of ["'A'","'B'","'C'","'D'"]) assert.match(migration,new RegExp(grade)); });
test("seed includes at least 15 fictional .example firms", () => { assert.ok((seed.match(/\.example/g)||[]).length>=15); assert.ok((seed.match(/'Seed data'/g)||[]).length>=15); });
test("Phase 2 schema stages discovery and preserves research evidence",()=>{for(const table of ["discovery_jobs","firm_candidates","research_evidence"])assert.match(phase2,new RegExp(`create table public\\.${table}`));assert.match(phase2,/security_invoker=true/);assert.match(phase2,/payroll_mentioned boolean/);});
test("candidate approval rechecks duplicates and converts in one database function",()=>{assert.match(phase2,/prepare_candidate/);assert.match(phase2,/approve_firm_candidate/);assert.match(phase2,/Candidate has a duplicate match/);});
test("duplicate detection uses exact domain, phone, name-city and fuzzy warning",()=>{const firms=[{id:"1",name:"Alamo Books & Tax",website:"https://alamobooks.com",phone:"210-555-0100",city:"San Antonio"}];assert.equal(detectDuplicate({name:"Anything",website:"https://www.alamobooks.com/services",phone:"",city:"Austin"},firms).status,"Exact Match");assert.equal(detectDuplicate({name:"Alamo Books and Tax PC",website:"",phone:"",city:"San Antonio"},firms).status,"Possible Match");assert.equal(normalizeDomain("https://www.Example.com/a"),"example.com");});
test("partner type recommendation covers referral, wholesale, CPA, bookkeeping and tax",()=>{const base={services:[],type:"Accounting Firm",smb:true};assert.equal(recommendPartnerType({...base,services:["Payroll"]}),"Wholesale Payroll Partner");assert.equal(recommendPartnerType({...base,type:"CPA Firm",services:["Bookkeeping"]}),"Strategic CPA Partner");assert.equal(recommendPartnerType({...base,type:"Bookkeeper",services:["Bookkeeping"]}),"Bookkeeping Partner");assert.equal(recommendPartnerType({...base,type:"Enrolled Agent",services:["Tax"]}),"Tax / EA Partner");});
test("mail merge eligibility enforces grade, primary email, and terminal outreach statuses",()=>{const firm={grade:"A",contacts:[{primary:true,email:"owner@example.com",emailStatus:"Verified"}],outreach:[]};assert.equal(isMailMergeEligible(firm),true);assert.equal(isMailMergeEligible({...firm,outreach:[{status:"Partner"}]}),false);assert.equal(isMailMergeEligible({...firm,grade:"C"}),false);});
test("controlled live-search batch stages 15 official San Antonio candidates",()=>{assert.equal((candidates.match(/make\("rc/g)||[]).length,15);assert.equal((candidates.match(/Official firm website/g)||[]).length,1);});
test("Google Places discovery is resumable, authenticated, and idempotent",async()=>{const discoveryMigration=await readFile(new URL("../supabase/migrations/20260812164327_google_places_discovery_backend.sql",import.meta.url),"utf8");const createRoute=await readFile(new URL("../app/api/discovery/jobs/route.ts",import.meta.url),"utf8");const tickRoute=await readFile(new URL("../app/api/discovery/jobs/[id]/tick/route.ts",import.meta.url),"utf8");assert.match(discoveryMigration,/unique \(source, source_record_id\)/i);assert.match(discoveryMigration,/create table public\.discovery_job_queries/i);assert.match(discoveryMigration,/enable row level security/i);assert.match(createRoute,/supabase\.auth\.getUser\(\)/);assert.match(tickRoute,/supabase\.auth\.getUser\(\)/);assert.match(tickRoute,/ignoreDuplicates:true/);assert.doesNotMatch(createRoute+tickRoute,/createAdminClient|SUPABASE_SERVICE_ROLE_KEY/);});
test("West Texas discovery is multi-anchor and respects the remaining candidate cap",async()=>{const markets=await readFile(new URL("../lib/discovery/markets.ts",import.meta.url),"utf8");const tickRoute=await readFile(new URL("../app/api/discovery/jobs/[id]/tick/route.ts",import.meta.url),"utf8");assert.match(markets,/West Texas/);for(const city of ["Midland","Odessa","Abilene","San Angelo","Lubbock"])assert.match(markets,new RegExp(city));assert.match(tickRoute,/target_candidates-job\.records_imported/);assert.match(tickRoute,/places\.slice\(0,remaining\)/);});
test("statewide discovery includes North Texas, Gulf Coast, and Far West Texas regional markets",async()=>{const markets=await readFile(new URL("../lib/discovery/markets.ts",import.meta.url),"utf8");const createRoute=await readFile(new URL("../app/api/discovery/jobs/route.ts",import.meta.url),"utf8");for(const region of ["North Texas","Gulf Coast","Far West Texas"])assert.match(markets,new RegExp(region));for(const city of ["Dallas","Fort Worth","Arlington","Plano","Frisco","Houston","Sugar Land","The Woodlands","Katy","Pearland","El Paso"])assert.match(markets,new RegExp(city));assert.match(createRoute,/max\(DISCOVERY_MARKETS\.length\)/);});
test("candidate contacts are staged with RLS and copied only by approval",async()=>{const staged=await readFile(new URL("../supabase/migrations/20260812190000_west_texas_candidate_contacts.sql",import.meta.url),"utf8");const route=await readFile(new URL("../app/api/discovery/candidates/[id]/contacts/research/route.ts",import.meta.url),"utf8");assert.match(staged,/create table public\.candidate_contacts/);assert.match(staged,/enable row level security/);assert.match(staged,/selected_for_approval/);assert.match(staged,/insert into public\.contacts/);assert.match(route,/supabase\.auth\.getUser\(\)/);assert.doesNotMatch(route,/SUPABASE_SERVICE_ROLE_KEY|createAdminClient/);});
test("Apollo contact research broadens by domain, ranks locally, and keeps enrichment capped",async()=>{const apollo=await readFile(new URL("../lib/discovery/apollo.ts",import.meta.url),"utf8");assert.match(apollo,/process\.env\.APOLLO_API_KEY/);assert.match(apollo,/x-api-key/);assert.match(apollo,/mixed_people\/api_search/);assert.match(apollo,/people\/match/);assert.match(apollo,/SEARCH_POOL_SIZE=25/);assert.match(apollo,/decisionMakerScore/);assert.match(apollo,/Math\.min\(Math\.max\(limit,1\),3\)/);assert.match(apollo,/directPhone:null/);assert.doesNotMatch(apollo,/person_seniorities|reveal_phone_number|NEXT_PUBLIC_APOLLO/);});
test("displayed phone numbers use a reusable click-to-dial link",async()=>{const phoneLink=await readFile(new URL("../components/phone-link.tsx",import.meta.url),"utf8");const network=await readFile(new URL("../components/partner-network.tsx",import.meta.url),"utf8");const discovery=await readFile(new URL("../components/discovery.tsx",import.meta.url),"utf8");assert.match(phoneLink,/href={`tel:\${dialable}`}/);assert.match(phoneLink,/replace\(\/\[\^\\d\+\]\/g,""\)/);assert.match(network,/PhoneLink phone={firm\.phone}/);assert.match(network,/PhoneLink phone={c\.phone}/);assert.match(discovery,/PhoneLink phone={c\.phone}/);assert.match(discovery,/PhoneLink phone={contact\.directPhone}/);});
test("firm overview links the website beside click-to-dial",async()=>{const network=await readFile(new URL("../components/partner-network.tsx",import.meta.url),"utf8");assert.match(network,/Info label="Phone" value={firm\.phone\?<PhoneLink/);assert.match(network,/Info label="Website" value={firm\.website\?<a className="firm-website-link"/);assert.match(network,/target="_blank" rel="noreferrer"/);});
test("bulk approval uses the existing candidate RPC and skips ineligible selections",async()=>{const discovery=await readFile(new URL("../components/discovery.tsx",import.meta.url),"utf8");assert.match(discovery,/const bulkEligible=selectedCandidates\.filter/);assert.match(discovery,/candidate\.duplicateStatus==="No Match"/);assert.match(discovery,/for\(const candidate of bulkEligible\)/);assert.match(discovery,/await approve\(candidate,false\)/);assert.match(discovery,/Confirm approval/);});
test("web research queue is RLS protected, capped daily, and claimed without duplicate workers",async()=>{const sql=await readFile(new URL("../supabase/migrations/20260813145754_automated_accounting_firm_web_research.sql",import.meta.url),"utf8");for(const table of ["candidate_research_runs","candidate_research_findings"])assert.match(sql,new RegExp(`create table public\\.${table}`));assert.match(sql,/enable row level security/g);assert.match(sql,/pg_advisory_xact_lock/);assert.match(sql,/for update skip locked/);assert.match(sql,/p_daily_limit/);assert.match(sql,/attempt_count<3/);assert.match(sql,/revoke all on function public\.claim_candidate_web_research/);});
test("Firecrawl research searches for URLs, scrapes visited pages, and fills Apollo gaps",async()=>{const worker=await readFile(new URL("../lib/discovery/web-research.ts",import.meta.url),"utf8");assert.match(worker,/api\.firecrawl\.dev\/v2/);assert.match(worker,/firecrawl\("search"/);assert.match(worker,/firecrawl\("scrape"/);assert.match(worker,/formats:\["markdown",\{type:"json"/);assert.match(worker,/metadata\?\.sourceURL\?\?metadata\?\.url\?\?requestedUrl/);assert.match(worker,/fallbackFindings\(markdown,url\)/);assert.match(worker,/fallbackContacts\(markdown,url,candidate\)/);assert.match(worker,/safeDomain\(url\)!==officialDomain/);assert.match(worker,/findWebsiteDecisionMakers/);assert.match(worker,/source_url:page\.url/);assert.match(worker,/source_text:f\.excerpt/);assert.match(worker,/provider:"Website"/);assert.match(worker,/if\(!contacts\.length&&process\.env\.APOLLO_API_KEY\)/);assert.doesNotMatch(worker,/description.*source_text|snippet.*source_text/);});
test("manual contact research checks full official contact pages before Apollo",async()=>{const route=await readFile(new URL("../app/api/discovery/candidates/[id]/contacts/research/route.ts",import.meta.url),"utf8");const worker=await readFile(new URL("../lib/discovery/web-research.ts",import.meta.url),"utf8");assert.match(route,/findWebsiteDecisionMakers\(candidate\)/);assert.match(route,/websiteContacts\.length\?\[\]:await findAndEnrichDecisionMakers/);assert.match(route,/provider:"Website"/);assert.match(worker,/onlyMainContent:!contactPage/);assert.match(worker,/\{0,2\}/);assert.match(worker,/pagePriority/);});
test("research review controls approval transfer and preserves citations",async()=>{const sql=await readFile(new URL("../supabase/migrations/20260813145754_automated_accounting_firm_web_research.sql",import.meta.url),"utf8");assert.match(sql,/review_status='Accepted'/);assert.match(sql,/insert into public\.research_evidence/);assert.match(sql,/insert into public\.firms[\s\S]*values[\s\S]*returning id into new_firm_id/);assert.match(sql,/selected_for_approval/);assert.match(sql,/Missing information remains Unknown|Human-reviewable/i);});
test("web research routes authenticate users and cron requires its secret",async()=>{const candidateRoute=await readFile(new URL("../app/api/discovery/candidates/[id]/web-research/route.ts",import.meta.url),"utf8");const reviewRoute=await readFile(new URL("../app/api/discovery/candidates/[id]/web-research/findings/route.ts",import.meta.url),"utf8");const cron=await readFile(new URL("../app/api/cron/web-research/route.ts",import.meta.url),"utf8");assert.match(candidateRoute,/auth\.getUser/);assert.match(reviewRoute,/auth\.getUser/);assert.match(cron,/process\.env\.CRON_SECRET/);assert.match(cron,/authorization/);});
test("completed zero-finding research can be retried after extraction improvements",async()=>{const panel=await readFile(new URL("../components/candidate-web-research-panel.tsx",import.meta.url),"utf8");assert.match(panel,/webResearchStatus==="Complete"&&Boolean\(lastRun\)&&findings\.length===0/);});
