"use client";
import { useMemo, useState, type FormEvent } from "react";
import { Check, Plus, ShieldCheck, Trash2, Users } from "lucide-react";
import type { AccessContext, AppRole, AssignmentStatus, Firm, FirmCandidate, TerritoryAccessLevel } from "@/lib/types";
import { assignFirms, removeUserTerritory, saveTerritory, setUserTerritory, updateProfileAccess } from "@/lib/supabase/access";
import { createClient } from "@/lib/supabase/client";
import { Select } from "@/components/form-controls";

type Props={access:AccessContext;firms:Firm[];candidates:FirmCandidate[];notify:(message:string)=>void;onChanged:()=>void};
const roles:AppRole[]=["Admin","Manager","Rep","Researcher"];
const levels:TerritoryAccessLevel[]=["View","Work","Manage"];
const statuses:AssignmentStatus[]=["Unassigned","Assigned","Working","On Hold","Closed"];

export function AdminAccess({access,firms,candidates,notify,onChanged}:Props){
  const [tab,setTab]=useState<"Users"|"Territories"|"Assignments">("Users");
  const [pending,setPending]=useState(false);const [email,setEmail]=useState("");const [fullName,setFullName]=useState("");
  const [userId,setUserId]=useState(access.profiles.find(p=>p.id!==access.currentUser.id)?.id??access.currentUser.id);
  const [territoryId,setTerritoryId]=useState(access.territories[0]?.id??"");const [level,setLevel]=useState<TerritoryAccessLevel>("View");
  const [firmIds,setFirmIds]=useState<string[]>([]);const [assignmentStatus,setAssignmentStatus]=useState<AssignmentStatus>("Assigned");
  const [territoryName,setTerritoryName]=useState("");const [territoryRegion,setTerritoryRegion]=useState("");
  const supabase=createClient();
  const counts=useMemo(()=>new Map(access.profiles.map(p=>[p.id,{firms:firms.filter(f=>f.assignedUserId===p.id).length,candidates:candidates.filter(c=>c.createdByUserId===p.id).length,outreach:firms.flatMap(f=>f.outreach).filter(o=>o.createdByUserId===p.id).length}])),[access.profiles,firms,candidates]);
  const refresh=()=>{onChanged();setPending(false)};
  const invite=async(e:FormEvent)=>{e.preventDefault();setPending(true);const response=await fetch("/api/admin/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,fullName})});const body=await response.json().catch(()=>({error:"Invitation failed."}));if(!response.ok){notify(body.error);setPending(false);return;}notify(`Invitation sent to ${email}`);setEmail("");setFullName("");refresh();};
  const changeProfile=async(id:string,role:AppRole,isActive:boolean,managerUserId?:string)=>{setPending(true);const result=await updateProfileAccess(supabase,id,{role,isActive,managerUserId});notify("error" in result?"User access could not be updated.":"User access updated");refresh();};
  const addTerritory=async(e:FormEvent)=>{e.preventDefault();setPending(true);const result=await saveTerritory(supabase,{name:territoryName,region:territoryRegion,state:"TX",isActive:true});notify("error" in result?"Territory could not be created.":"Territory created");setTerritoryName("");setTerritoryRegion("");refresh();};
  const grant=async()=>{setPending(true);const result=await setUserTerritory(supabase,userId,territoryId,level);notify("error" in result?"Territory access could not be saved.":"Territory access saved");refresh();};
  const remove=async(id:string)=>{setPending(true);const result=await removeUserTerritory(supabase,id);notify("error" in result?"Territory access could not be removed.":"Territory access removed");refresh();};
  const assign=async()=>{if(!firmIds.length)return;setPending(true);const result=await assignFirms(supabase,firmIds,userId||null,assignmentStatus);notify("error" in result?"Firms could not be assigned.":`${result.count} firm${result.count===1?"":"s"} updated`);setFirmIds([]);refresh();};
  const managerOptions=[{value:"",label:"No manager"},...access.profiles.filter(p=>p.isActive&&p.role==="Manager").map(p=>({value:p.id,label:p.fullName}))];
  return <section className="page admin-page"><div className="page-title compact"><div><span className="eyebrow">ACCESS CONTROL</span><h1>Administration</h1><p>Manage people, territories, and prospect ownership.</p></div></div>
    <div className="tabs">{(["Users","Territories","Assignments"] as const).map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</div>
    {tab==="Users"&&<><form className="panel admin-form" onSubmit={invite}><h2>Invite a user</h2><input aria-label="Full name" placeholder="Full name" value={fullName} onChange={e=>setFullName(e.target.value)} required/><input aria-label="Email" type="email" placeholder="Email address" value={email} onChange={e=>setEmail(e.target.value)} required/><button className="primary" disabled={pending}><Plus size={16}/>Send invite</button></form><div className="panel admin-list">{access.profiles.map(profile=>{const own=profile.id===access.currentUser.id;const stats=counts.get(profile.id);return <div className="admin-row" key={profile.id}><div className="avatar">{profile.fullName.split(" ").map(x=>x[0]).slice(0,2).join("")}</div><div className="admin-identity"><b>{profile.fullName}</b><span>{profile.email}</span><small>{stats?.firms??0} firms · {stats?.candidates??0} candidates · {stats?.outreach??0} outreach</small></div><Select value={profile.role} disabled={own} onChange={value=>changeProfile(profile.id,value as AppRole,profile.isActive,profile.managerUserId)} options={roles}/>{(profile.role==="Rep"||profile.role==="Researcher")&&<Select value={profile.managerUserId??""} onChange={value=>changeProfile(profile.id,profile.role,profile.isActive,value)} options={managerOptions}/>}<label className="admin-toggle"><input type="checkbox" checked={profile.isActive} disabled={own} onChange={e=>changeProfile(profile.id,profile.role,e.target.checked,profile.managerUserId)}/>Active</label></div>})}</div></>}
    {tab==="Territories"&&<><form className="panel admin-form" onSubmit={addTerritory}><h2>Add territory</h2><input aria-label="Territory name" placeholder="Territory name" value={territoryName} onChange={e=>setTerritoryName(e.target.value)} required/><input aria-label="Region mapping" placeholder="Region mapping" value={territoryRegion} onChange={e=>setTerritoryRegion(e.target.value)} required/><button className="primary" disabled={pending}><Plus size={16}/>Add</button></form><div className="panel admin-list">{access.territories.map(t=><div className="admin-row" key={t.id}><ShieldCheck size={18}/><div className="admin-identity"><b>{t.name}</b><span>{t.region} · {t.state}</span></div><i className={`status ${t.isActive?"contacted":"new"}`}>{t.isActive?"Active":"Inactive"}</i></div>)}</div></>}
    {tab==="Assignments"&&<div className="admin-grid"><div className="panel admin-form"><h2>Territory access</h2><Select value={userId} onChange={setUserId} options={access.profiles.filter(p=>p.isActive).map(p=>({value:p.id,label:p.fullName}))}/><Select value={territoryId} onChange={setTerritoryId} options={access.territories.map(t=>({value:t.id,label:t.name}))}/><Select value={level} onChange={v=>setLevel(v as TerritoryAccessLevel)} options={levels}/><button className="primary" disabled={pending||!userId||!territoryId} onClick={grant}><Check size={16}/>Save access</button>{access.assignments.map(a=><div className="access-chip" key={a.id}><span>{access.profiles.find(p=>p.id===a.userId)?.fullName} · {access.territories.find(t=>t.id===a.territoryId)?.name} · {a.accessLevel}</span><button aria-label="Remove territory access" disabled={pending} onClick={()=>remove(a.id)}><Trash2 size={14}/></button></div>)}</div><div className="panel admin-form"><h2>Assign firms</h2><Select value={userId} onChange={setUserId} options={access.profiles.filter(p=>p.isActive).map(p=>({value:p.id,label:p.fullName}))}/><Select value={assignmentStatus} onChange={v=>setAssignmentStatus(v as AssignmentStatus)} options={statuses}/><div className="assignment-picker">{firms.map(f=><label key={f.id}><input type="checkbox" checked={firmIds.includes(f.id)} onChange={e=>setFirmIds(ids=>e.target.checked?[...ids,f.id]:ids.filter(id=>id!==f.id))}/><span>{f.name}</span><small>{f.city}</small></label>)}</div><button className="primary" disabled={pending||!firmIds.length} onClick={assign}><Users size={16}/>Assign {firmIds.length||"selected"}</button></div></div>}
  </section>;
}
