"use client";
import { useState } from "react";
import { AlertTriangle, Check, ChevronDown, ChevronUp, ExternalLink, FileSearch, Loader2, RotateCw, X } from "lucide-react";
import type { FirmCandidate } from "@/lib/types";

type FindingRow={id:string;category:string;attribute_name:string;proposed_value:unknown;source_url:string;source_text:string;confidence:"High"|"Medium"|"Low";review_status:"Pending"|"Accepted"|"Rejected"};
type RunRow={id:string;status:string;attempt_count:number;pages_visited:number;provider_requests:number;error_code:string|null};
const labels:Record<string,string>={provides_tax:"Tax services",provides_bookkeeping:"Bookkeeping",provides_accounting:"Accounting",provides_payroll:"Payroll",provides_cas:"CAS",provides_business_advisory:"Advisory",provides_audit:"Audit",provides_quickbooks_services:"QuickBooks",xero_partner:"Xero",smb_focus:"SMB focus",spanish_speaking:"Spanish-language support",industry_specialties:"Industries",firm_types:"Firm type",business_client_focus:"Business-client focus",suggested_conversation_angle:"Partnership angle",phone:"Phone",address_line_1:"Address",about_page_url:"About page",services_page_url:"Services page",leadership_page_url:"Leadership page",contact_page_url:"Contact page"};
function valueText(value:unknown){if(typeof value==="boolean")return value?"Yes":"No";if(Array.isArray(value))return value.join(", ");if(typeof value==="string")return value;return JSON.stringify(value);}

export function CandidateWebResearchPanel({candidate,onRefresh,notify}:{candidate:FirmCandidate;onRefresh:()=>Promise<void>;notify:(message:string)=>void}){
  const[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[pending,setPending]=useState(false),[runs,setRuns]=useState<RunRow[]>([]),[findings,setFindings]=useState<FindingRow[]>([]),[error,setError]=useState("");
  const load=async()=>{setLoading(true);setError("");try{const response=await fetch(`/api/discovery/candidates/${candidate.id}/web-research`,{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error();setRuns(body.runs??[]);setFindings(body.findings??[]);}catch{setError("Research details could not be loaded.");}finally{setLoading(false);}};
  const toggle=()=>{const next=!open;setOpen(next);if(next)void load();};
  const queue=async()=>{setPending(true);setError("");try{const response=await fetch(`/api/discovery/candidates/${candidate.id}/web-research`,{method:"POST"});const body=await response.json();if(!response.ok)throw new Error(body.error);notify("Candidate queued for web research");await onRefresh();await load();}catch(e){setError(e instanceof Error&&e.message?e.message:"Candidate could not be queued.");}finally{setPending(false);}};
  const review=async(findingId:string,status:"Accepted"|"Rejected")=>{setPending(true);try{const response=await fetch(`/api/discovery/candidates/${candidate.id}/web-research/findings`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({findingId,status})});if(!response.ok)throw new Error();const next=findings.map(item=>item.id===findingId?{...item,review_status:status}:item);setFindings(next);if(next.every(item=>item.review_status!=="Pending"))await onRefresh();}catch{setError("This finding could not be updated.");}finally{setPending(false);}};
  const acceptHigh=async()=>{setPending(true);try{const response=await fetch(`/api/discovery/candidates/${candidate.id}/web-research/findings`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({acceptHighConfidence:true})});if(!response.ok)throw new Error();const next:FindingRow[]=findings.map(item=>item.review_status==="Pending"&&item.confidence==="High"?{...item,review_status:"Accepted"}:item);setFindings(next);if(next.every(item=>item.review_status!=="Pending"))await onRefresh();notify("High-confidence findings accepted");}catch{setError("High-confidence findings could not be accepted.");}finally{setPending(false);}};
  const groups=Map.groupBy(findings,item=>item.category),lastRun=runs[0],canQueue=["Not Queued","Failed","Invalid Domain","Daily Limit"].includes(candidate.webResearchStatus)||(candidate.webResearchStatus==="Complete"&&Boolean(lastRun)&&findings.length===0);
  return <div className="web-research-panel"><button className="web-research-toggle" onClick={toggle}><FileSearch size={14}/><span>Web research</span><i className={`web-status ws-${candidate.webResearchStatus.toLowerCase().replaceAll(" ","-")}`}>{candidate.webResearchStatus}</i>{open?<ChevronUp size={14}/>:<ChevronDown size={14}/>}</button>{open&&<div className="web-research-body">
    <div className="web-research-summary"><span>{lastRun?`${lastRun.pages_visited} visited pages · ${lastRun.attempt_count} attempt${lastRun.attempt_count===1?"":"s"}`:"No research run yet"}</span><div>{findings.some(f=>f.review_status==="Pending"&&f.confidence==="High")&&<button disabled={pending} onClick={acceptHigh}><Check size={13}/>Accept high-confidence findings</button>}{canQueue&&<button disabled={pending||!candidate.domain} onClick={queue}><RotateCw size={13}/>{pending?"Queueing…":candidate.webResearchStatus==="Not Queued"?"Research now":"Retry"}</button>}</div></div>
    {loading&&<p className="research-panel-message"><Loader2 className="spin" size={14}/>Loading cited findings…</p>}{error&&<p className="research-panel-message error"><AlertTriangle size={14}/>{error}</p>}
    {!loading&&[...groups].map(([category,items])=><section className="finding-group" key={category}><h4>{category}</h4>{items.map(finding=><article className={`research-finding rf-${finding.review_status.toLowerCase()}`} key={finding.id}><div><b>{labels[finding.attribute_name]??finding.attribute_name.replaceAll("_"," ")}</b><strong>{valueText(finding.proposed_value)}</strong><p>{finding.source_text}</p><a href={finding.source_url} target="_blank" rel="noreferrer">View source <ExternalLink size={11}/></a></div><span className={`confidence c-${finding.confidence.toLowerCase()}`}>{finding.confidence}</span><div className="finding-actions"><button aria-label="Accept finding" className={finding.review_status==="Accepted"?"active accept":"accept"} disabled={pending} onClick={()=>review(finding.id,"Accepted")}><Check size={14}/></button><button aria-label="Reject finding" className={finding.review_status==="Rejected"?"active reject":"reject"} disabled={pending} onClick={()=>review(finding.id,"Rejected")}><X size={14}/></button></div></article>)}</section>)}
    {!loading&&findings.length===0&&candidate.webResearchStatus==="Complete"&&<p className="research-panel-message">The visited pages did not contain supported facts. Missing information remains Unknown.</p>}{lastRun?.error_code&&<p className="research-panel-message error"><AlertTriangle size={14}/>Research stopped: {lastRun.error_code.replaceAll("-"," ")}.</p>}
  </div>}</div>;
}
