import { ArrowUpRight, Building2, CalendarClock, Radar, Users } from "lucide-react";
import type { AccessContext, Firm, FirmCandidate } from "@/lib/types";
const today=new Date().toISOString().slice(0,10);const weekAgo=new Date(Date.now()-7*86400000).toISOString().slice(0,10);

export function MyWork({access,firms,candidates,choose}:{access:AccessContext;firms:Firm[];candidates:FirmCandidate[];choose:(firm:Firm)=>void}){
  const me=access.currentUser.id;
  const assigned=firms.filter(f=>f.assignedUserId===me);const top=assigned.filter(f=>f.topTarget).sort((a,b)=>b.score-a.score);const followups=assigned.flatMap(f=>f.outreach.filter(o=>o.nextFollowUp&&o.nextFollowUp<=today).map(o=>({firm:f,item:o})));const mine=candidates.filter(c=>c.createdByUserId===me);const privateResearch=mine.filter(c=>c.visibility==="Private");const outreachWeek=firms.flatMap(f=>f.outreach).filter(o=>o.createdByUserId===me&&o.date>=weekAgo).length;
  const leadership=access.currentUser.role==="Admin"||access.currentUser.role==="Manager";
  return <section className="page"><div className="page-title compact"><div><span className="eyebrow">PERSONAL WORKSPACE</span><h1>My Work</h1><p>Assignments, follow-ups, private research, and recent activity.</p></div></div><div className="metrics"><WorkMetric label="Assigned firms" value={assigned.length} icon={Building2}/><WorkMetric label="Top targets" value={top.length} icon={ArrowUpRight}/><WorkMetric label="Follow-ups due" value={followups.length} icon={CalendarClock}/><WorkMetric label="Outreach this week" value={outreachWeek} icon={Users}/></div><div className="dashboard-grid"><div className="panel opportunities"><div className="panel-head"><div><h2>My top targets</h2><p>Highest-scoring assigned prospects</p></div></div><div className="opportunity-list">{top.slice(0,8).map(f=><button key={f.id} onClick={()=>choose(f)}><div><b>{f.name}</b><span>{f.city} · {f.assignmentStatus}</span></div><strong>{f.score}</strong><ArrowUpRight size={16}/></button>)}</div></div><div className="panel"><div className="panel-head"><div><h2>My research</h2><p>Private and owned candidates</p></div></div><div className="work-summary"><p><Radar size={16}/><b>{mine.length}</b> candidates created</p><p><Radar size={16}/><b>{privateResearch.length}</b> private research records</p><p><CalendarClock size={16}/><b>{followups.length}</b> follow-ups due</p></div></div></div>{leadership&&<div className="panel team-work"><div className="panel-head"><div><h2>Team work</h2><p>Assignment and activity snapshot</p></div></div>{access.profiles.filter(p=>p.isActive).map(p=><div className="admin-row" key={p.id}><div className="admin-identity"><b>{p.fullName}</b><span>{p.role}</span></div><span>{firms.filter(f=>f.assignedUserId===p.id).length} firms</span><span>{firms.flatMap(f=>f.outreach).filter(o=>o.createdByUserId===p.id&&o.date>=weekAgo).length} outreach this week</span></div>)}</div>}</section>;
}
function WorkMetric({label,value,icon:Icon}:{label:string;value:number;icon:typeof Building2}){return <div className="metric"><div className="metric-icon blue"><Icon size={19}/></div><span>{label}</span><strong>{value}</strong><small>Visible to you</small></div>}
