"use client";
/* eslint-disable react-hooks/exhaustive-deps */

import { useMemo, useRef, useState, type ReactNode } from "react";
import { useRouter } from "next/navigation";
import { Activity, ArrowDownToLine, ArrowLeft, ArrowUpRight, Building2, CalendarClock, Check, ChevronDown, CircleUserRound, Download, FileSpreadsheet, LayoutDashboard, LogOut, Mail, MapPin, Menu, Plus, Radar, Search, SlidersHorizontal, Sparkles, Upload, Users, X } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import type { Activity as Outreach, Contact, DiscoveryJob, Firm, FirmCandidate, Grade } from "@/lib/types";
import { Discovery } from "@/components/discovery";
import { ContactForm } from "@/components/contact-form";
import { OutreachForm } from "@/components/outreach-form";
import { FirmEnrichmentForm } from "@/components/firm-enrichment-form";
import { ReadinessPanel } from "@/components/readiness-panel";
import { MissingInfoChecklist } from "@/components/missing-info-checklist";
import { ResearchEvidencePanel } from "@/components/research-evidence-panel";
import { Modal, Select } from "@/components/form-controls";
import { PhoneLink } from "@/components/phone-link";
import { isMailMergeEligible } from "@/lib/discovery/core.mjs";
import { DISCOVERY_REGIONS } from "@/lib/discovery/markets";

type View = "Dashboard"|"Discovery"|"Firms"|"Contacts"|"Outreach"|"Imports";
const nav: {label:View;icon:typeof LayoutDashboard}[]=[{label:"Dashboard",icon:LayoutDashboard},{label:"Discovery",icon:Radar},{label:"Firms",icon:Building2},{label:"Contacts",icon:Users},{label:"Outreach",icon:Activity},{label:"Imports",icon:FileSpreadsheet}];
const regions=DISCOVERY_REGIONS;
const gradeClass=(g:Grade)=>`grade grade-${g.replace("+","plus").toLowerCase()}`;
const lastActivity=(firm:Firm)=>[...firm.outreach].sort((a,b)=>b.date.localeCompare(a.date))[0];
const initials=(name:string)=>name.split(" ").map(x=>x[0]).slice(0,2).join("");
const externalUrl=(value:string)=>/^https?:\/\//i.test(value)?value:`https://${value}`;

type PartnerNetworkProps={initialFirms:Firm[];initialCandidates:FirmCandidate[]|null;initialJobs:DiscoveryJob[]|null;discoveryFailed:boolean};

export function PartnerNetwork({initialFirms,initialCandidates,initialJobs,discoveryFailed}:PartnerNetworkProps){
  const router=useRouter();
  const [view,setView]=useState<View>("Dashboard"); const [firms,setFirms]=useState(initialFirms);
  const [selected,setSelected]=useState<Firm|null>(null); const [query,setQuery]=useState("");
  const [region,setRegion]=useState("All regions"); const [grade,setGrade]=useState("All grades");
  const [service,setService]=useState("All services"); const [partnerType,setPartnerType]=useState("All partner types");
  const [topTargetsOnly,setTopTargetsOnly]=useState(false); const [needsContactOnly,setNeedsContactOnly]=useState(false); const [needsEmailOnly,setNeedsEmailOnly]=useState(false);
  const [sort,setSort]=useState("Total score"); const [page,setPage]=useState(1); const [savedView,setSavedView]=useState("All prospects");
  const [showFilters,setShowFilters]=useState(false); const [modal,setModal]=useState<"contact"|"outreach"|"import"|null>(null);
  const [modalFirmId,setModalFirmId]=useState<string|null>(null);
  const [toast,setToast]=useState(""); const [mobileNav,setMobileNav]=useState(false); const fileRef=useRef<HTMLInputElement>(null);
  const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2800)};
  const signOut=async()=>{const supabase=createClient();await supabase.auth.signOut();window.location.href="/login"};
  const onFirmApproved=(firm:Firm)=>{setFirms(fs=>fs.some(f=>f.id===firm.id)?fs.map(f=>f.id===firm.id?firm:f):[firm,...fs]);router.refresh()};
  const onFirmUpdated=(firm:Firm)=>{setFirms(fs=>fs.some(f=>f.id===firm.id)?fs.map(f=>f.id===firm.id?firm:f):[firm,...fs]);router.refresh()};
  const hasEmail=(f:Firm)=>f.contacts.some(c=>Boolean(c.email)&&c.emailStatus!=="Invalid");
  const matchesSaved=(f:Firm)=>savedView==="All prospects"||(savedView==="Top Targets"&&f.topTarget)||(savedView==="Top Targets — Need Enrichment"&&f.topTarget&&f.outreachReadinessScore<10)||(savedView==="Referral Opportunities"&&f.partnerType==="Referral Payroll Partner")||(savedView==="Wholesale Opportunities"&&f.partnerType==="Wholesale Payroll Partner")||(savedView==="Strategic CPA Partners"&&f.partnerType==="Strategic CPA Partner")||(savedView==="A+ Prospects"&&f.grade==="A+")||(savedView==="Ready for Outreach"&&isMailMergeEligible(f));
  const filtered=useMemo(()=>firms.filter(f=>`${f.name} ${f.city} ${f.contacts.map(c=>c.email).join(" ")}`.toLowerCase().includes(query.toLowerCase())&&(region==="All regions"||f.region===region)&&(grade==="All grades"||(grade==="A+ Only"&&f.grade==="A+")||(grade==="A or Better"&&(f.grade==="A+"||f.grade==="A"))||f.grade===grade)&&(service==="All services"||f.services.includes(service))&&(partnerType==="All partner types"||f.partnerType===partnerType)&&(!topTargetsOnly||f.topTarget)&&(!needsContactOnly||!f.contacts.some(c=>c.decisionMaker))&&(!needsEmailOnly||!hasEmail(f))&&matchesSaved(f)).sort((a,b)=>sort==="Firm name"?a.name.localeCompare(b.name):sort==="City"?a.city.localeCompare(b.city):sort==="Fit score"?b.partnerFitScore-a.partnerFitScore:sort==="Opportunity score"?b.partnershipOpportunityScore-a.partnershipOpportunityScore:sort==="Readiness score"?b.outreachReadinessScore-a.outreachReadinessScore:sort==="Grade"?b.score-a.score:b.score-a.score),[firms,query,region,grade,service,partnerType,topTargetsOnly,needsContactOnly,needsEmailOnly,sort,savedView]);
  const pageRows=filtered.slice((page-1)*8,page*8); const contacts=firms.flatMap(f=>f.contacts.map(c=>({...c,firm:f}))); const activities=firms.flatMap(f=>f.outreach.map(a=>({...a,firm:f}))).sort((a,b)=>b.date.localeCompare(a.date));
  const choose=(f:Firm)=>{setSelected(f);setView("Firms")};
  const exportCsv=(rows:Firm[])=>{const header=["First Name","Last Name","Firm Name","Title","Email","City","Region","Firm Type","Partner Grade","Payroll Offered","Bookkeeping Offered","CAS Offered","Website","Phone","Personalization Note"];const lines=[header,...rows.flatMap(f=>f.contacts.filter(c=>c.email).map(c=>[c.firstName,c.lastName,f.name,c.title,c.email,f.city,f.region,f.type,f.grade,f.services.includes("Payroll")?"Yes":"No",f.services.includes("Bookkeeping")?"Yes":"No",f.services.includes("CAS")?"Yes":"No",f.website,f.phone,f.personalizationNote]))];const csv=lines.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="sotex-mail-merge.csv";a.click();notify(`Exported ${lines.length-1} eligible contacts`)};

  return <div className="app-shell">
    <aside className={`sidebar ${mobileNav?"open":""}`}>
      <div className="brand"><div className="brand-mark">S</div><div><b>SoTex</b><span>Partner Network</span></div><button className="icon-btn mobile-close" onClick={()=>setMobileNav(false)}><X size={18}/></button></div>
      <nav>{nav.map(({label,icon:Icon})=><button key={label} className={view===label&&!selected?"active":""} onClick={()=>{setView(label);setSelected(null);setMobileNav(false)}}><Icon size={18}/><span>{label}</span>{label==="Firms"&&<em>{firms.length}</em>}</button>)}</nav>
      <div className="sidebar-foot"><div className="data-status"><span/><div><b>Data workspace</b><small>Live data · read-only</small></div></div><div className="profile"><div className="avatar">SR</div><div><b>SoTex Research</b><span>Internal team</span></div><button className="sign-out-btn" onClick={signOut} title="Sign out"><LogOut size={15}/></button></div></div>
    </aside>
    <main>
      <header className="topbar"><button className="icon-btn menu-btn" onClick={()=>setMobileNav(true)}><Menu size={20}/></button><div className="global-search"><Search size={17}/><input aria-label="Global search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search firms, contacts, cities..."/><kbd>⌘ K</kbd></div><button className="icon-btn"><CalendarClock size={19}/></button><button className="avatar small">SR</button></header>
      {selected?<FirmDetail firm={selected} setFirm={f=>{setFirms(fs=>fs.map(x=>x.id===f.id?f:x));setSelected(f);router.refresh()}} back={()=>setSelected(null)} openModal={m=>{setModalFirmId(selected.id);setModal(m)}} notify={notify}/>:<>
        {view==="Dashboard"&&<Dashboard firms={firms} choose={choose} setView={setView}/>}
        {view==="Discovery"&&<Discovery initialCandidates={initialCandidates} jobs={initialJobs} discoveryFailed={discoveryFailed} onFirmApproved={onFirmApproved} notify={notify}/>}
        {view==="Firms"&&<FirmsPage rows={pageRows} total={filtered.length} firmsCount={firms.length} region={region} setRegion={setRegion} grade={grade} setGrade={setGrade} service={service} setService={setService} partnerType={partnerType} setPartnerType={setPartnerType} topTargetsOnly={topTargetsOnly} setTopTargetsOnly={setTopTargetsOnly} needsContactOnly={needsContactOnly} setNeedsContactOnly={setNeedsContactOnly} needsEmailOnly={needsEmailOnly} setNeedsEmailOnly={setNeedsEmailOnly} sort={sort} setSort={setSort} page={page} setPage={setPage} choose={choose} showFilters={showFilters} setShowFilters={setShowFilters} exportCsv={()=>exportCsv(filtered)} savedView={savedView} setSavedView={setSavedView} />}
        {view==="Contacts"&&<ContactsPage contacts={contacts} add={()=>{setModalFirmId(null);setModal("contact")}} choose={choose}/>}
        {view==="Outreach"&&<OutreachPage items={activities} add={()=>{setModalFirmId(null);setModal("outreach")}} choose={choose}/>}
        {view==="Imports"&&<ImportsPage fileRef={fileRef} onFile={e=>{if(e.target.files?.[0])setModal("import")}}/>}
      </>}
    </main>
    {modal==="contact"&&<ContactForm firms={firms} lockedFirmId={modalFirmId??undefined} close={()=>setModal(null)} onCreated={onFirmUpdated} notify={notify}/>}
    {modal==="outreach"&&<OutreachForm firms={firms} lockedFirmId={modalFirmId??undefined} close={()=>setModal(null)} onLogged={onFirmUpdated} notify={notify}/>}
    {modal==="import"&&<ImportPreview close={()=>setModal(null)} commit={()=>{setModal(null);notify("Import batch committed")}}/>}
    {toast&&<div className="toast"><Check size={17}/>{toast}</div>}
  </div>
}

function Dashboard({firms,choose,setView}:{firms:Firm[];choose:(f:Firm)=>void;setView:(v:View)=>void}){
  const counts={A:firms.filter(f=>f.grade==="A+"||f.grade==="A").length,B:firms.filter(f=>f.grade==="B").length,contacts:firms.filter(f=>f.contacts.length).length,missing:firms.filter(f=>!f.contacts.length).length,contacted:firms.filter(f=>f.outreach.length).length,interested:firms.filter(f=>f.outreach.some(o=>o.status==="Interested")).length,meetings:firms.filter(f=>f.outreach.some(o=>o.status==="Meeting Scheduled")).length,partners:firms.filter(f=>f.outreach.some(o=>o.status==="Partner")).length};
  const opportunities=firms.filter(f=>!f.outreach.length).sort((a,b)=>b.score-a.score).slice(0,6);
  if(!firms.length) return <section className="page"><div className="page-title"><div><span className="eyebrow">Tuesday, August 11</span><h1>Good morning, SoTex</h1><p>Here’s the health of your partner pipeline across Texas.</p></div><button className="primary" onClick={()=>setView("Firms")}><Plus size={17}/>Add prospect</button></div>
    <div className="empty"><Building2 size={24}/><h3>No firms yet</h3><p>Firms will appear here once they&apos;re added to your Supabase database.</p></div>
  </section>
  return <section className="page"><div className="page-title"><div><span className="eyebrow">Tuesday, August 11</span><h1>Good morning, SoTex</h1><p>Here’s the health of your partner pipeline across Texas.</p></div><button className="primary" onClick={()=>setView("Firms")}><Plus size={17}/>Add prospect</button></div>
    <div className="metrics"><Metric label="Total firms" value={firms.length} note={`Across ${regions.length} regions`} icon={Building2}/><Metric label="A+/A prospects" value={counts.A} note="Highest potential" icon={Sparkles} tone="gold"/><Metric label="B prospects" value={counts.B} note="Worth prioritizing" icon={ArrowUpRight} tone="blue"/><Metric label="Contacts found" value={counts.contacts} note={`${counts.missing} firms still missing`} icon={CircleUserRound} tone="green"/></div>
    <div className="dashboard-grid"><div className="panel pipeline"><div className="panel-head"><div><h2>Pipeline overview</h2><p>From research to active partnership</p></div><button>Last 30 days <ChevronDown size={14}/></button></div><div className="pipeline-row">{[["Not contacted",firms.length-counts.contacted,"#9aa9b5"],["Contacted",counts.contacted,"#66c8f1"],["Interested",counts.interested,"#3ab1e9"],["Meetings",counts.meetings,"#146ff8"],["Partners",counts.partners,"#002c4d"]].map(([l,v,c])=><div key={String(l)}><div className="bar" style={{height:`${38+Number(v)*8}px`,background:String(c)}}/><b>{v}</b><span>{l}</span></div>)}</div></div>
      <div className="panel regions"><div className="panel-head"><div><h2>Regional coverage</h2><p>Prospects by target market</p></div></div>{regions.map(r=>{const n=firms.filter(f=>f.region===r).length;return <div className="region-row" key={r}><span>{r}</span><div><i style={{width:`${Math.max(12,n/firms.length*240)}px`}}/></div><b>{n}</b></div>})}</div></div>
    <div className="panel opportunities"><div className="panel-head"><div><h2>Priority opportunities</h2><p>Highest-scoring prospects without outreach</p></div><button className="link-btn" onClick={()=>setView("Firms")}>View all <ArrowUpRight size={15}/></button></div><div className="opportunity-list">{opportunities.length?opportunities.map(f=><button key={f.id} onClick={()=>choose(f)}><div className="company-icon">{initials(f.name)}</div><div><b>{f.name}</b><span><MapPin size={12}/>{f.city} · {f.type}</span></div><div className="service-pills">{f.services.slice(0,2).map(s=><i key={s}>{s}</i>)}</div><div className="score"><strong>{f.score}</strong><span>Score</span></div><span className={gradeClass(f.grade)}>{f.grade}</span><ArrowUpRight size={17}/></button>):<Empty title="No open opportunities" text="Every firm has outreach logged, or there are no firms yet."/>}</div></div>
  </section>
}

function Metric({label,value,note,icon:Icon,tone="sage"}:{label:string;value:number;note:string;icon:typeof Building2;tone?:string}){return <div className="metric"><div className={`metric-icon ${tone}`}><Icon size={19}/></div><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}

function FirmsPage({rows,total,firmsCount,region,setRegion,grade,setGrade,service,setService,partnerType,setPartnerType,topTargetsOnly,setTopTargetsOnly,needsContactOnly,setNeedsContactOnly,needsEmailOnly,setNeedsEmailOnly,sort,setSort,page,setPage,choose,showFilters,setShowFilters,exportCsv,savedView,setSavedView}:{rows:Firm[];total:number;firmsCount:number;region:string;setRegion:(x:string)=>void;grade:string;setGrade:(x:string)=>void;service:string;setService:(x:string)=>void;partnerType:string;setPartnerType:(x:string)=>void;topTargetsOnly:boolean;setTopTargetsOnly:(x:boolean)=>void;needsContactOnly:boolean;setNeedsContactOnly:(x:boolean)=>void;needsEmailOnly:boolean;setNeedsEmailOnly:(x:boolean)=>void;sort:string;setSort:(x:string)=>void;page:number;setPage:(x:number)=>void;choose:(f:Firm)=>void;showFilters:boolean;setShowFilters:(x:boolean)=>void;exportCsv:()=>void;savedView:string;setSavedView:(x:string)=>void}){
  return <section className="page firms-page"><div className="page-title compact"><div><span className="eyebrow">PROSPECT DATABASE</span><h1>Firms</h1><p>{total} prospects match your current view.</p></div><div className="actions"><button onClick={exportCsv}><Download size={16}/>Export</button><button className="primary" disabled title="Adding firms isn't connected to the database yet"><Plus size={17}/>Add firm</button></div></div>
    <div className="saved-view-bar"><span>Saved views</span><Select value={savedView} onChange={setSavedView} options={["All prospects","Top Targets","Top Targets — Need Enrichment","Referral Opportunities","Wholesale Opportunities","Strategic CPA Partners","A+ Prospects","Ready for Outreach"]}/>{savedView!=="All prospects"&&<button onClick={()=>setSavedView("All prospects")}><X size={13}/>Clear view</button>}</div><div className="filterbar"><Select value={region} onChange={setRegion} options={["All regions",...regions]}/><Select value={grade} onChange={setGrade} options={["All grades","A+ Only","A or Better","A","B","C","D"]}/><Select value={service} onChange={setService} options={["All services","Tax","Bookkeeping","Payroll","CAS","QuickBooks"]}/><Select value={partnerType} onChange={setPartnerType} options={["All partner types","Strategic CPA Partner","Referral Payroll Partner","Wholesale Payroll Partner","Bookkeeping Partner","Tax / EA Partner","Needs Research","Low Fit"]}/><button className={showFilters?"active-filter":""} onClick={()=>setShowFilters(!showFilters)}><SlidersHorizontal size={16}/>More filters</button><div className="sorter">Sort: <Select value={sort} onChange={setSort} options={["Total score","Fit score","Opportunity score","Readiness score","Grade","Firm name","City"]}/></div></div>
    {showFilters&&<div className="advanced"><label><input type="checkbox" checked={topTargetsOnly} onChange={e=>setTopTargetsOnly(e.target.checked)}/> Top Targets</label><label><input type="checkbox" checked={needsContactOnly} onChange={e=>setNeedsContactOnly(e.target.checked)}/> Needs contact enrichment</label><label><input type="checkbox" checked={needsEmailOnly} onChange={e=>setNeedsEmailOnly(e.target.checked)}/> Needs email</label><button onClick={()=>{setRegion("All regions");setGrade("All grades");setService("All services");setPartnerType("All partner types");setTopTargetsOnly(false);setNeedsContactOnly(false);setNeedsEmailOnly(false)}}>Clear all</button></div>}
    <div className="table-card scoring-table">{rows.length?<><div className="table-scroll"><table><thead><tr><th>Firm</th><th>City</th><th>Type</th><th>Partner Type</th><th>Fit</th><th>Opportunity</th><th>Readiness</th><th>Total</th><th>Grade</th><th>Top Target</th><th>Primary Contact</th><th>Email</th><th>Outreach Status</th><th/></tr></thead><tbody>{rows.map(f=>{const c=f.contacts.find(contact=>contact.primary)??f.contacts[0],last=lastActivity(f);return <tr key={f.id} onClick={()=>choose(f)}><td><div className="firm-cell"><div className="company-icon small-icon">{initials(f.name)}</div><div><b>{f.name}</b><span>{f.employees??"—"} employees</span></div></div></td><td><b className="normal">{f.city}</b><span>{f.region}</span></td><td>{f.type}</td><td><span className="partner-type-pill">{f.partnerType||"Needs Research"}</span></td><td><b>{f.partnerFitScore}</b><span>/60</span></td><td><b>{f.partnershipOpportunityScore}</b><span>/25</span></td><td><b>{f.outreachReadinessScore}</b><span>/15</span></td><td><strong>{f.score}</strong></td><td><span className={gradeClass(f.grade)}>{f.grade}</span></td><td>{f.topTarget?<span className="top-target">🔥 Top Target</span>:"—"}</td><td>{c?<b className="normal">{c.firstName} {c.lastName}</b>:<span className="missing">Contact missing</span>}</td><td>{c?.email?<span>{c.email}</span>:<span className="missing">Email missing</span>}</td><td><span className={`status ${last?"contacted":"new"}`}>{last?.status||"Not contacted"}</span></td><td><ArrowUpRight size={16}/></td></tr>})}</tbody></table></div><div className="pagination"><span>Showing {(page-1)*8+1}–{Math.min(page*8,total)} of {total}</span><div><button disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><button disabled={page*8>=total} onClick={()=>setPage(page+1)}>Next</button></div></div></>:<Empty title={firmsCount===0?"No firms yet":"No matches"} text={firmsCount===0?"Firms will appear here once they're added to your Supabase database.":"Try adjusting your search or filters."}/>}</div>
  </section>
}

function FirmDetail({firm,setFirm,back,openModal,notify}:{firm:Firm;setFirm:(f:Firm)=>void;back:()=>void;openModal:(m:"contact"|"outreach")=>void;notify:(s:string)=>void}){
  const [editing,setEditing]=useState(false); const [tab,setTab]=useState("Overview");
  return <section className="page detail"><button className="back" onClick={back}><ArrowLeft size={16}/>All firms</button><div className="detail-head"><div className="company-icon large">{initials(firm.name)}</div><div className="detail-name"><div><h1>{firm.name}</h1><span className={gradeClass(firm.grade)}>Grade {firm.grade}</span><span className={`priority p-${firm.priority.toLowerCase()}`}>{firm.priority} priority</span></div><p><MapPin size={14}/>{firm.city}, {firm.state} · {firm.region} <i/> {firm.website&&<a href={externalUrl(firm.website)} target="_blank" rel="noreferrer">Visit website <ArrowUpRight size={12}/></a>}</p></div><div className="actions"><button onClick={()=>setEditing(true)}>Edit firm</button><button className="primary" onClick={()=>openModal("outreach")}><Plus size={16}/>Log outreach</button></div></div>
    <div className="tabs">{["Overview","Contacts","Outreach","Evidence","Notes"].map(t=><button key={t} onClick={()=>setTab(t)} className={tab===t?"active":""}>{t}{t==="Contacts"&&<em>{firm.contacts.length}</em>}{t==="Outreach"&&<em>{firm.outreach.length}</em>}</button>)}</div>
    {tab==="Overview"&&<div className="detail-grid"><div><div className="panel info-panel"><div className="panel-head"><h2>Firm overview</h2></div><div className="info-grid"><Info label="Firm type" value={firm.type}/><Info label="Team size" value={firm.employees?`${firm.employees} employees`:"Unknown"}/><Info label="Phone" value={firm.phone?<PhoneLink phone={firm.phone}/>:"Unknown"}/><Info label="Website" value={firm.website?<a className="firm-website-link" href={externalUrl(firm.website)} target="_blank" rel="noreferrer">Visit website <ArrowUpRight size={13}/></a>:"Unknown"}/><Info label="Research status" value={firm.researchStatus}/><Info label="Data confidence" value={firm.confidence}/></div></div><div className="panel services-panel"><div className="panel-head"><h2>Services & capabilities</h2></div><div className="service-grid">{["Tax","Bookkeeping","Accounting","Payroll","CAS","Audit","Business advisory","QuickBooks","Spanish speaking","SMB focus"].map(s=>{const yes=firm.services.includes(s)||(s==="Spanish speaking"&&firm.spanish)||(s==="SMB focus"&&firm.smb);return <div className={yes?"yes":""} key={s}><span>{yes?<Check size={14}/>:<X size={14}/>}</span>{s}</div>})}</div></div><ReadinessPanel firm={firm}/><MissingInfoChecklist firm={firm}/></div>
      <aside><PartnershipScore firm={firm}/></aside></div>}
    {tab==="Contacts"&&<div className="panel tab-panel"><div className="panel-head"><div><h2>Firm contacts</h2><p>Decision makers and relationship owners</p></div><button className="primary" onClick={()=>openModal("contact")}><Plus size={16}/>Add contact</button></div>{firm.contacts.length?firm.contacts.map(c=><div className="contact-row" key={c.id}><div className="avatar">{initials(`${c.firstName} ${c.lastName}`)}</div><div><b>{c.firstName} {c.lastName}</b><span>{c.title}</span></div>{c.primary&&<i>Primary</i>}{c.email&&<a href={`mailto:${c.email}`}><Mail size={15}/>{c.email}</a>}{c.phone&&<PhoneLink phone={c.phone}/>}</div>):<Empty title="No contacts yet" text="Add an owner, partner, or other decision maker."/>}</div>}
    {tab==="Outreach"&&<div className="panel tab-panel"><div className="panel-head"><div><h2>Outreach timeline</h2><p>Every touchpoint with this firm</p></div><button className="primary" onClick={()=>openModal("outreach")}><Plus size={16}/>Log activity</button></div>{firm.outreach.length?firm.outreach.map(o=><div className="timeline" key={o.id}><div className="timeline-icon"><Mail size={15}/></div><div><b>{o.type} · {o.status}</b><span>{o.date}</span><p>{o.notes}</p>{o.nextFollowUp&&<i>Follow up {o.nextFollowUp}</i>}</div></div>):<Empty title="No outreach logged" text="This is a clean opportunity. Add the first touchpoint."/>}</div>}
    {tab==="Evidence"&&<ResearchEvidencePanel firm={firm} notify={notify} key={`evidence-${firm.id}`}/>}
    {tab==="Notes"&&<div className="panel tab-panel"><div className="panel-head"><div><h2>Internal notes</h2><p>Private context for your team</p></div></div><textarea defaultValue={firm.notes} rows={8}/><button className="primary" disabled title="Saving notes isn't connected to the database yet" onClick={()=>notify("Notes saved")}>Save notes</button></div>}
    {editing&&<FirmEnrichmentForm firm={firm} close={()=>setEditing(false)} onUpdated={f=>{setFirm(f);setEditing(false)}} notify={notify}/>}
  </section>
}

function ContactsPage({contacts,add,choose}:{contacts:(Contact&{firm:Firm})[];add:()=>void;choose:(f:Firm)=>void}){return <section className="page"><div className="page-title compact"><div><span className="eyebrow">RELATIONSHIP MAP</span><h1>Contacts</h1><p>{contacts.length} people across your prospect network.</p></div><button className="primary" onClick={add}><Plus size={17}/>Add contact</button></div><div className="contact-grid">{contacts.map(c=><article className="contact-card" key={c.id}><button className="contact-card-open" onClick={()=>choose(c.firm)}><div className="avatar large-avatar">{initials(`${c.firstName} ${c.lastName}`)}</div><span className={gradeClass(c.firm.grade)}>{c.firm.grade}</span><h3>{c.firstName} {c.lastName}</h3><p>{c.title}</p><b>{c.firm.name}</b><small><MapPin size={12}/>{c.firm.city}</small></button>{c.email&&<a href={`mailto:${c.email}`}><Mail size={14}/>{c.email}</a>}{c.phone&&<PhoneLink phone={c.phone}/>}</article>)}</div></section>}
function OutreachPage({items,add,choose}:{items:(Outreach&{firm:Firm})[];add:()=>void;choose:(f:Firm)=>void}){return <section className="page"><div className="page-title compact"><div><span className="eyebrow">ENGAGEMENT HISTORY</span><h1>Outreach</h1><p>Track conversations, responses, and follow-ups.</p></div><button className="primary" onClick={add}><Plus size={17}/>Log outreach</button></div><div className="panel outreach-list">{items.map(o=><button key={o.id} onClick={()=>choose(o.firm)}><div className="timeline-icon"><Mail size={15}/></div><div><b>{o.firm.name}</b><span>{o.type} · {o.notes}</span></div><i className={`status ${o.status==="Interested"?"contacted":"new"}`}>{o.status}</i><time>{o.date}</time><ArrowUpRight size={16}/></button>)}</div></section>}
function ImportsPage({fileRef,onFile}:{fileRef:React.RefObject<HTMLInputElement|null>;onFile:(e:React.ChangeEvent<HTMLInputElement>)=>void}){const sample="firm_name,website,phone,address,city,state,zip,region,firm_type,employee_count,provides_tax,provides_bookkeeping,provides_payroll,provides_cas,smb_focus,spanish_speaking,first_name,last_name,title,email,direct_phone,linkedin_url,source,notes\nExample Ledger Co,https://example.com,2105550100,100 Main St,San Antonio,TX,78205,San Antonio,CPA Firm,8,true,true,false,true,true,false,Jamie,Reed,Owner,jamie@example.com,2105550101,,Referral,Sample row";return <section className="page imports"><div className="page-title compact"><div><span className="eyebrow">DATA OPERATIONS</span><h1>Imports</h1><p>Bring firms and contacts into your network safely.</p></div></div><div className="import-layout"><div className="dropzone"><input ref={fileRef} type="file" accept=".csv" disabled onChange={onFile}/><div><Upload size={24}/></div><h2>Upload a CSV file</h2><p>Imports aren&apos;t connected to the database yet.</p><button className="primary" disabled title="Imports aren't connected to the database yet">Choose CSV</button><small>Maximum file size 10 MB</small></div><div className="panel import-help"><h2>Import checklist</h2>{["Normalize firm names and domains","Detect duplicate domains","Check firm name + city matches","Validate contact email duplicates","Preview before committing"].map(x=><p key={x}><Check size={15}/>{x}</p>)}<a href={`data:text/csv;charset=utf-8,${encodeURIComponent(sample)}`} download="sotex-import-template.csv"><ArrowDownToLine size={16}/>Download sample CSV</a></div></div><div className="panel empty-history"><FileSpreadsheet size={25}/><h3>No import batches yet</h3><p>Completed imports will appear here with row counts and audit details.</p></div></section>}

function Info({label,value}:{label:string;value:ReactNode}){return <div><span>{label}</span><b>{value}</b></div>}
function Empty({title,text}:{title:string;text:string}){return <div className="empty"><Users size={24}/><h3>{title}</h3><p>{text}</p></div>}

function PartnershipScore({firm}:{firm:Firm}){
  const breakdown=firm.scoringBreakdown;
  return <div className="score-card partnership-score-card">
    <div className="score-top"><div><span>PARTNERSHIP SCORE</span><strong>{firm.score}<small>/100</small></strong></div><div className={gradeClass(firm.grade).replace("grade ","grade-orb ")}>{firm.grade}<span>GRADE</span></div></div>
    <div className="score-track"><i style={{width:`${firm.score}%`}}/></div>
    <div className="score-identifiers"><div><span>Partner type</span><b>{firm.partnerType||"Needs Research"}</b></div><div><span>Top Target</span><b>{firm.topTarget?"🔥 Top Target":"No"}</b></div></div>
    <ScoreSection title="Partner Fit" score={firm.partnerFitScore} max={60} items={breakdown.partnerFit.items}/>
    <ScoreSection title="Partnership Opportunity" score={firm.partnershipOpportunityScore} max={25} items={breakdown.partnershipOpportunity.items}/>
    <ScoreSection title="Outreach Readiness" score={firm.outreachReadinessScore} max={15} items={breakdown.outreachReadiness.items}/>
    <div className="score-breakdown-section adjustments"><div className="score-breakdown-heading"><h3>Adjustments</h3><strong>{breakdown.adjustmentTotal}</strong></div>{breakdown.adjustments.length?<ul>{breakdown.adjustments.map((item,index)=><li key={`${item.label}-${index}`}><span>{item.points}</span>{item.label}</li>)}</ul>:<p>No negative adjustments.</p>}</div>
    <div className="approach"><span>Conversation angle</span><p>{firm.suggestedConversationAngle||"Research the firm further before selecting an outreach angle."}</p></div>
  </div>
}

function ScoreSection({title,score,max,items}:{title:string;score:number;max:number;items:{points:number;label:string}[]}){
  return <div className="score-breakdown-section"><div className="score-breakdown-heading"><h3>{title}</h3><strong>{score} / {max}</strong></div><ul>{items.length?items.map((item,index)=><li className={item.points===0?"score-needed":""} key={`${item.label}-${index}`}><span>{item.points>0?`+${item.points}`:"—"}</span>{item.label}</li>):<li className="score-needed"><span>—</span>No supported signals yet</li>}</ul></div>
}

function ImportPreview({close,commit}:{close:()=>void;commit:()=>void}){return <Modal title="Import preview" subtitle="Review how 24 CSV rows will be handled." close={close}><div className="preview-stats"><div><strong>17</strong><span>New firms</span></div><div><strong>3</strong><span>Possible duplicates</span></div><div><strong>14</strong><span>New contacts</span></div><div className="warn"><strong>4</strong><span>Invalid rows</span></div></div><div className="duplicate"><div><b>Possible duplicate</b><span>Alamo Ledger Partners · San Antonio</span></div><i>Domain match</i></div><div className="duplicate"><div><b>Invalid record</b><span>Row 19 · Missing firm_name</span></div><i className="bad">Required field</i></div><div className="modal-actions"><button onClick={close}>Cancel</button><button className="primary" onClick={commit}>Import 17 firms</button></div></Modal>}
