import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import { findAndEnrichDecisionMakers } from "@/lib/discovery/apollo";
import { createAdminClient } from "@/lib/supabase/server";

type ClaimedRun={id:string;firm_candidate_id:string;attempt_count:number};
type CandidateRow={id:string;firm_name:string;website:string|null;domain:string|null;city:string;state:string;review_status:string};
type ExtractedFinding={category:string;attributeName:string;value:unknown;excerpt:string;confidence:"High"|"Medium"|"Low"};
type ExtractedContact={fullName?:string;firstName?:string;lastName?:string;title?:string;email?:string;phone?:string;linkedinUrl?:string;excerpt?:string;confidence?:"High"|"Medium"|"Low"};
type PageExtraction={url:string;findings:ExtractedFinding[];contacts:ExtractedContact[]};
type FirecrawlResponse={payload:Record<string,unknown>;credits:number};

const SCHEMA={type:"object",properties:{findings:{type:"array",items:{type:"object",properties:{category:{type:"string"},attributeName:{type:"string"},value:{},excerpt:{type:"string"},confidence:{type:"string",enum:["High","Medium","Low"]}},required:["category","attributeName","value","excerpt","confidence"]}},contacts:{type:"array",items:{type:"object",properties:{fullName:{type:"string"},firstName:{type:"string"},lastName:{type:"string"},title:{type:"string"},email:{type:"string"},phone:{type:"string"},linkedinUrl:{type:"string"},excerpt:{type:"string"},confidence:{type:"string",enum:["High","Medium","Low"]}}}}},required:["findings","contacts"]};
const PROMPT=`Extract only facts explicitly stated on this visited page about the accounting firm. Never infer a negative from missing text. Return no finding for unknown facts. Allowed attributes: provides_tax, provides_bookkeeping, provides_accounting, provides_payroll, provides_cas, provides_business_advisory, provides_audit, provides_quickbooks_services, xero_partner, smb_focus, spanish_speaking, industry_specialties, phone, address_line_1, about_page_url, services_page_url, leadership_page_url, contact_page_url, firm_types, business_client_focus, suggested_conversation_angle. Boolean service findings must only be true when supported. Include a short verbatim supporting excerpt. Extract public leaders and decision makers with title and any public email, phone, or LinkedIn URL.`;
const ALLOWED_CATEGORIES=new Set(["Services","Client Focus","Industries","Language","Firm Profile","Contact Details","Important Pages","Partnership","Leadership"]);
const BOOLEAN_ATTRIBUTES=new Set(["provides_tax","provides_bookkeeping","provides_accounting","provides_payroll","provides_cas","provides_business_advisory","provides_audit","provides_quickbooks_services","xero_partner","smb_focus","spanish_speaking"]);
const ARRAY_ATTRIBUTES=new Set(["industry_specialties","firm_types"]);
const TEXT_ATTRIBUTES=new Set(["phone","address_line_1","about_page_url","services_page_url","leadership_page_url","contact_page_url","business_client_focus","suggested_conversation_angle"]);

function safeDomain(value:string){try{const url=new URL(value.includes("://")?value:`https://${value}`);const host=url.hostname.toLowerCase().replace(/^www\./,"");if(!host||host==="localhost"||host.endsWith(".local")||/^\d+\.\d+\.\d+\.\d+$/.test(host))return null;return host;}catch{return null;}}
function providerError(status:number){const error=new Error("Provider request failed") as Error&{code:string;transient:boolean};error.code=status===402?"credits-exhausted":status===429?"rate-limited":status>=500?"provider-unavailable":"provider-rejected";error.transient=status===429||status>=500;return error;}
async function firecrawl(path:string,body:unknown):Promise<FirecrawlResponse>{const key=process.env.FIRECRAWL_API_KEY;if(!key){const error=new Error("Firecrawl is not configured") as Error&{code:string;transient:boolean};error.code="not-configured";error.transient=false;throw error;}const response=await fetch(`https://api.firecrawl.dev/v2/${path}`,{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify(body),signal:AbortSignal.timeout(90000)});if(!response.ok)throw providerError(response.status);const payload=await response.json() as Record<string,unknown>;return{payload,credits:typeof payload.creditsUsed==="number"?payload.creditsUsed:1};}
function webResults(payload:Record<string,unknown>){const data=payload.data as {web?:unknown[]}|unknown[]|undefined;if(Array.isArray(data))return data as Record<string,unknown>[];return Array.isArray(data?.web)?data.web as Record<string,unknown>[]:[];}
function extractionFrom(result:Record<string,unknown>):PageExtraction|null{const url=String(result.url??(result.metadata as Record<string,unknown>|undefined)?.sourceURL??"");const json=result.json as {findings?:unknown[];contacts?:unknown[]}|undefined;if(!url||!json)return null;const findings=(Array.isArray(json.findings)?json.findings:[]).filter((f):f is ExtractedFinding=>{if(!f||typeof f!=="object")return false;const x=f as Record<string,unknown>;if(typeof x.attributeName!=="string"||typeof x.excerpt!=="string"||!x.excerpt.trim()||typeof x.category!=="string"||!ALLOWED_CATEGORIES.has(x.category))return false;if(BOOLEAN_ATTRIBUTES.has(x.attributeName))return x.value===true;if(ARRAY_ATTRIBUTES.has(x.attributeName))return Array.isArray(x.value)&&x.value.every(value=>typeof value==="string");if(TEXT_ATTRIBUTES.has(x.attributeName))return typeof x.value==="string"&&x.value.trim().length>0;return false;});const contacts=(Array.isArray(json.contacts)?json.contacts:[]).filter((c):c is ExtractedContact=>Boolean(c&&typeof c==="object"));return{url,findings,contacts};}
function normalizedUrl(value:unknown){if(typeof value!=="string"||!value.trim())return null;try{const url=new URL(value.includes("://")?value:`https://${value}`);if(!["http:","https:"].includes(url.protocol))return null;url.hash="";return url.toString();}catch{return null;}}
function scrapeUrls(candidate:CandidateRow,official:Record<string,unknown>[],publicResults:Record<string,unknown>[],domain:string){const urls:string[]=[];const add=(value:unknown)=>{const url=normalizedUrl(value);if(url&&!urls.includes(url))urls.push(url);};add(candidate.website||`https://${domain}`);for(const result of official){const url=normalizedUrl(result.url);if(url&&safeDomain(url)===domain)add(url);}for(const result of publicResults)add(result.url);return urls.slice(0,6);}
async function researchPages(candidate:CandidateRow):Promise<{pages:PageExtraction[];requests:number;credits:number}>{const domain=safeDomain(candidate.domain||candidate.website||"");if(!domain){const e=new Error("Invalid domain") as Error&{code:string;transient:boolean};e.code="invalid-domain";e.transient=false;throw e;}const official=await firecrawl("search",{query:`${candidate.firm_name} accounting services leadership contact`,includeDomains:[domain],limit:5,sources:["web"]});const publicSearch=await firecrawl("search",{query:`"${candidate.firm_name}" ${candidate.city} ${candidate.state} accounting leadership services`,limit:3,sources:["web"]});const urls=scrapeUrls(candidate,webResults(official.payload),webResults(publicSearch.payload),domain);const pages:PageExtraction[]=[];let requests=2;let credits=official.credits+publicSearch.credits;let lastError:unknown;
  for(const url of urls){try{const scraped=await firecrawl("scrape",{url,formats:[{type:"json",schema:SCHEMA,prompt:PROMPT}],onlyMainContent:true,timeout:60000});requests+=1;credits+=scraped.credits;const data=scraped.payload.data;if(data&&typeof data==="object"&&!Array.isArray(data)){const page=extractionFrom(data as Record<string,unknown>);if(page)pages.push(page);}}catch(error){lastError=error;}}
  if(urls.length>0&&pages.length===0&&lastError)throw lastError;
  return{pages:[...new Map(pages.map(page=>[page.url,page])).values()],requests,credits};}
function contactKey(contact:ExtractedContact){return `${(contact.email||"").toLowerCase()}|${(contact.linkedinUrl||"").toLowerCase()}|${(contact.fullName||`${contact.firstName||""} ${contact.lastName||""}`).toLowerCase()}`;}
function usableDecisionMaker(contact:ExtractedContact){return Boolean((contact.fullName||contact.firstName||contact.lastName)&&contact.title&&(contact.email||contact.phone||contact.linkedinUrl));}

async function persistResult(supabase:SupabaseClient,run:ClaimedRun,candidate:CandidateRow,pages:PageExtraction[],requests:number,credits:number){
  const findings=pages.flatMap(page=>page.findings.map(f=>({firm_candidate_id:candidate.id,research_run_id:run.id,category:f.category,attribute_name:f.attributeName,proposed_value:f.value,source_url:page.url,source_text:f.excerpt.slice(0,1000),confidence:f.confidence||"Medium"})));
  if(findings.length){const{error}=await supabase.from("candidate_research_findings").upsert(findings,{onConflict:"research_run_id,attribute_name,source_url,source_text",ignoreDuplicates:true});if(error)throw error;}
  const contacts=[...new Map(pages.flatMap(page=>page.contacts.map(c=>({...c,sourceUrl:page.url}))).filter(usableDecisionMaker).map(c=>[contactKey(c),c])).values()];
  if(contacts.length){const rows=contacts.map((c,index)=>({firm_candidate_id:candidate.id,provider:"Website",provider_record_id:contactKey(c),first_name:c.firstName??null,last_name:c.lastName??null,full_name:(c.fullName??[c.firstName,c.lastName].filter(Boolean).join(" "))||null,normalized_name:(c.fullName??[c.firstName,c.lastName].filter(Boolean).join(" ")).toLowerCase().replace(/[^a-z0-9]+/g," ").trim()||null,title:c.title??null,role_category:"Decision Maker",email:c.email??null,email_status:c.email?"Unverified":"Not Found",direct_phone:c.phone??null,phone_status:c.phone?"Unverified":"Not Found",linkedin_url:c.linkedinUrl??null,confidence:c.confidence??"Medium",is_primary_contact:index===0,is_decision_maker:true,selected_for_approval:true,source_url:c.sourceUrl,raw_data:{excerpt:c.excerpt??null}}));const{error}=await supabase.from("candidate_contacts").upsert(rows,{onConflict:"firm_candidate_id,provider,provider_record_id"});if(error)throw error;}
  if(!contacts.length&&process.env.APOLLO_API_KEY){const apollo=await findAndEnrichDecisionMakers(candidate.domain||candidate.website||"",3);if(apollo.length){const rows=apollo.map((c,index)=>({firm_candidate_id:candidate.id,provider:"Apollo",provider_record_id:c.providerRecordId,first_name:c.firstName,last_name:c.lastName,full_name:c.fullName,normalized_name:c.fullName?.toLowerCase().replace(/[^a-z0-9]+/g," ").trim(),title:c.title,role_category:c.roleCategory,email:c.email,email_status:c.emailStatus,direct_phone:c.directPhone,phone_status:c.phoneStatus,linkedin_url:c.linkedinUrl,confidence:c.confidence,is_primary_contact:index===0,is_decision_maker:true,selected_for_approval:true,source_url:c.sourceUrl,raw_data:c.rawData}));await supabase.from("candidate_contacts").upsert(rows,{onConflict:"firm_candidate_id,provider,provider_record_id"});}}
  const now=new Date().toISOString();await supabase.from("candidate_research_runs").update({status:"Complete",completed_at:now,provider_requests:requests,provider_credits:credits,pages_visited:pages.length}).eq("id",run.id);await supabase.from("firm_candidates").update({web_research_status:findings.length?"Needs Review":"Complete",web_researched_at:now,web_research_error_code:null}).eq("id",candidate.id);
}
async function failRun(supabase:SupabaseClient,run:ClaimedRun,candidateId:string,error:unknown){const code=error&&typeof error==="object"&&"code" in error?String(error.code):"unknown";const transient=Boolean(error&&typeof error==="object"&&"transient" in error&&(error as {transient:unknown}).transient);const retry=transient&&run.attempt_count<3;const available=new Date(Date.now()+Math.min(30,2**run.attempt_count)*60000).toISOString();await supabase.from("candidate_research_runs").update({status:retry?"Retry":"Failed",available_at:available,error_code:code,...(!retry?{completed_at:new Date().toISOString()}:{})}).eq("id",run.id);await supabase.from("firm_candidates").update({web_research_status:code==="invalid-domain"?"Invalid Domain":retry?"Queued":"Failed",web_research_error_code:code,...(!retry?{web_researched_at:new Date().toISOString()}:{})}).eq("id",candidateId);}

export async function processWebResearchQueue(maxCandidates=3){const supabase=createAdminClient();const daily=Math.max(1,Number(process.env.WEB_RESEARCH_DAILY_CANDIDATE_LIMIT??30));const{data:runs,error}=await supabase.rpc("claim_candidate_web_research",{p_limit:Math.min(maxCandidates,daily),p_daily_limit:daily});if(error)throw error;const claimed=(runs??[]) as ClaimedRun[];const processRun=async(run:ClaimedRun)=>{const{data:candidate}=await supabase.from("firm_candidates").select("id,firm_name,website,domain,city,state,review_status").eq("id",run.firm_candidate_id).single<CandidateRow>();if(!candidate||!["New","Needs Review"].includes(candidate.review_status)){await failRun(supabase,run,run.firm_candidate_id,{code:"not-researchable",transient:false});return;}await supabase.from("firm_candidates").update({web_research_status:"Researching"}).eq("id",candidate.id);try{const result=await researchPages(candidate);await persistResult(supabase,run,candidate,result.pages,result.requests,result.credits);}catch(runError){const code=runError&&typeof runError==="object"&&"code" in runError?String(runError.code):"unknown";console.error(`[Web Research] candidate failed (code: ${code})`);await failRun(supabase,run,candidate.id,runError);}};for(let offset=0;offset<claimed.length;offset+=3)await Promise.all(claimed.slice(offset,offset+3).map(processRun));return{claimed:claimed.length};}
